# Generated by Django 5.1.4 on 2025-01-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("photo1_url", models.URLField()),
                ("photo2_url", models.URLField()),
                ("score", models.FloatField()),
                ("ranking", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
